### ISSUE TITLE
E22 Modlist

### ISSUE THREAD

**Issue by Castone22** [Erisia/builder#127]
[modpack.txt](https://github.com/Erisia/builder/files/2637478/modpack.txt)

Current modlist above, please comment on mods that you would like added or removed in this thread.

Definitely Staying (Vetoed by Me)
- The Aether
- Tropicraft (Between these two and chromaticraft there will be PLENTY of exploration in the pack)
- BigReactors (Friendly on the server and easy, so people tend to default to it, if you don't like it don't use it)

Adding
- Gapling hook mod
- Pam's Harvestcraft
- Minechem (We don't get to play with this much in SMP)
- Opis, Eira, Dynmap and some other clientside stuff is included in our default erisia package, so don't worry much about these.
- Aroma's dimension
- Atlasmod 
- Tardismod

Not Adding
- Natura (Redwoods are evil for the server... i'm sorry)
- Enderzoo (More mobs when we already have the aether is a bad idea)
- Draconic Evolution (Doesn't play nicely with hardcore ender expansion until 1.10+)
- Mystcraft (Mystcraft's world loading is hard on the server compared to rftools, so i'd rather use it.  However even rftools is pretty bad in 1.7)
- Smartmovement (Buggy when using modded ladders and such)

Removing
- Twilight Forest (Retrogen is bad in 1.7 mmkay?)
- Animania
- Plant Megapack (Pam's is a better choice here)
- Fancy Fluid Storage (I've caused world corruptions with this)
- Crayfish's Furniture Mod (World Corruptions)
- Hunger Overhaul (Leaving Applecore)
- MovingWorld
- RemainInMotion (Both of these have a lot of known dupes and crashes)
- Roguelike (Low key mod that kills the server DURING run time due to high density of mob spawners)

Up for Debate so far
- Realistic Terraingen (Breaks CrC progression since it won't spawn ocean temples, unless there's a way to get it to spawn oceans or something)
- Better Sorage vs Iron Backpacks
- Artifacts 
- ArsMagica2 
- Gany's Nether

**Comment by Maxwell-lt** [comment]
**Remove:**
PlantMegaPack

**Add:**
Backlytra
Actually Additions (maybe? I doubt the 1.7.10 feature set is that strong)

And I vote for keeping Loot Bags, those are great for early-game mob farms.

**Comment by darqen27** [comment]
Loot bags can stay, if they cause problems. then go

**Comment by Roonas** [comment]
**Remove:**

PlantMegaPack

BigReactors - We have Mekanism, and Rotarycraft, and Thermal Expansion, and EnderIO, and IE, do we really need this?

Fancy Fluid Storage - Known to cause bugs, we have Extra Cells.

GregsLighting - We have Repower and IE which covers this function.

**HungerOverhaul** - Duh.

movingworld - Spoopy moving blocks.

MrCrayfishFurnitureMod - buggy and corruptiony.

OpenModularTurrets - who uses these, also, lumen turrets.

FlamingoMod - Needless fluff.

PlaceableGunpowder - Why tho?

**roguelike** - Makes world gen ugly, lag, tps, etc.

moarcarts - We have Railcraft and Steves carts.

RemainInMotion - Spoopy moving blocks.

**tropicraft - We have 3 dimension mods, pick one?

twilightforest

TheAether**

**Comment by Maxwell-lt** [comment]
In response to @Roonas, I vote to not remove Rougelike Dungeons, since that will provide a serious exploration outlet for Burper and I, each dungeon large enough that we won't have to be travelling dozens of kilometers per play session to continuously explore.

Out of the three dimension mods, The Aether II appears to be the most sensible to hold on to, as TF is very common in packs, and Tropicraft sounds boring.

**Comment by darqen27** [comment]
@Roonas I second this remove list.

**Comment by lashtear** [comment]
BigReactors is more tick-friendly than some of the other options, I _think_.

ActuallyAdditions is 1.10+ iirc(??)

# Things I would add:
TardisMod - promotes off-overworld machinery, profoundly useful
MineChem - hilariously OP but fun and educational
NetherOres - make mining the nether fun, profitable, and hilariously explosive.
Natura - helps make the nether a lot less dull, more trees.
Gany's Nether - useful nether plants
RealisticTerrainGenerator - because vanilla gen is ugly.
AdminCommandsToolbox + Opis - so we can diagnose inevitable problems
BetterChests - low tick farm automation
Aroma's Dimensional World - for stripmining without damaging our pretty overworld
Metallurgy - more complicated ores & alloys; greatly expands TiCo options
EnderZoo - wither witches, concussion creepers, enderminis and fallen knights
BetterRain - light-weight mod that dramatically improves the wet atmospherics

# Things to consider:
DynMap on the server?
MystCraft - because we ALWAYS need more dimension mods!
MagicalCrops - straightforward, albeit grindy solutions
BetterStorage - those backpacks are so cute!
Smart Moving - much better pre-flight exploration experience
ArsMagica2 - yet another magic system
Artifacts - More interesting ruins to explore and useful tools like Cyclic has in 1.12

# Things I think someone else will miss and add later:
Pam's Harvestcraft + Harvest the Nether
Draconic Evolution - though I'd be happy to see it go...
StreamsMod
RuinsMod

# Things I'll add locally but might be good optionals:
Better Foliage

# Configuration details to verify:
Morpheus - may be problematic with vampires o,,o but probably still a good idea

**Comment by Theburper** [comment]
I'd like to echo support for leaving roguelike in. Same with loot bags. 
Also, voting to only have one dimension mod, specifically Aether.
Finally, I'd like to vote against adding TARDIS mod.

**Comment by darqen27** [comment]
I vote to add tardis mod

**Comment by TheJizzy** [comment]
I would add:

**ArsMagica 2** 
EnderZoo
Aroma1997s Dimensional World
Natura 
Pam's Harvestcraft

Remove:

PlantMegaPack
Rougelike Dungeons
**HungerOverhaul** 
TheAether

**Comment by lashtear** [comment]
I specifically like better storage when configured so the backpack doesn't require a slot and is openable via a (configured) hotkey.  The little cupboards are nice too, and otherwise tough to replace in 1.7.  I don't know iron backpacks but I'm okay using it-- no big deal either way.

We should investigated RTG+CrC -- anyone have both handy and ready to test with those in isolation?  If it works, great!  If it doesn't, we'll either need to provide some other means of doing that part of the progression OR (more likely) not using RTG.  It really is better than vanilla worldgen though...

[Ars Magica 2](https://minecraft.curseforge.com/projects/ars-magica-2) is a very nice customizable magic system where you sorta make your own spells.  I expect @Theburper especially would like it because of the many boss fights involved in its progression.  It is more-content though, and if we're trying to thin...

[Gany's Nether](https://minecraft.curseforge.com/projects/ganys-nether) provides various nether farming options and resulting cheaper access to certain resources.  See [their wiki](http://ganys-nether.wikia.com/wiki/Category:Nether_Crops) for examples.  If those seem to OP, then we should probably avoid it.  Gany has other mods (AOBD, which we have) and the Surface/End extensions, similar to this one.  I like those a lot less though.  The surface one in particular makes the animals leave 💩 everywhere.

**Comment by Castone22** [comment]
I see no reason why not and yeah, it should be fine, we've done it that way before

**Comment by Baughn** [comment]
I wonder if it's possible to restrict the Roguelike dungeons to just one particular world.

If not, then maybe Battle Towers? They're eyesores, but that means it's easy to avoid living next to one. At a sufficiently low spawn rate, they shouldn't get involved unless you seek them out, and I recall having a lot of fun fighting through one using AM2 spells.

**Comment by the-vindex** [comment]
Update after today:
**[No work there, did not touch]**
The Aether
Tropicraft (Between these two and chromaticraft there will be PLENTY of exploration in the pack)
BigReactors (Friendly on the server and easy, so people tend to default to it, if you don't like it don't use it)
Adding

Gapling hook mod **[Done]**
Pam's Harvestcraft **[Done]**
Minechem (We don't get to play with this much in SMP) **[Done]**
Opis, Eira, Dynmap and some other clientside stuff is included in our default erisia package, so don't worry much about these. **[Partially done, did not check in detail what we usually add vs what is actually in]**
Aroma's dimension **[Done]**
Atlasmod **[Done]**
Tardismod **[Done]**

**[No work there, did not touch]**
Not Adding

Natura (Redwoods are evil for the server... i'm sorry)
Enderzoo (More mobs when we already have the aether is a bad idea)
Draconic Evolution (Doesn't play nicely with hardcore ender expansion until 1.10+)
Mystcraft (Mystcraft's world loading is hard on the server compared to rftools, so i'd rather use it. However even rftools is pretty bad in 1.7)
Smartmovement (Buggy when using modded ladders and such)


Removing

Twilight Forest (Retrogen is bad in 1.7 mmkay?)  **[Done]**
Animania  **[Done, was not even there]**
Plant Megapack (Pam's is a better choice here) **[Done, was not even there]**
Fancy Fluid Storage (I've caused world corruptions with this) **[Done]**
Crayfish's Furniture Mod (World Corruptions) **[Done]**
Hunger Overhaul (Leaving Applecore) **[Done]**
MovingWorld **[Done]**
RemainInMotion (Both of these have a lot of known dupes and crashes) **[Done]**
Roguelike (Low key mod that kills the server DURING run time due to high density of mob spawners) **[Done]**

**[Did not touch these]**
Up for Debate so far

Realistic Terraingen (Breaks CrC progression since it won't spawn ocean temples, unless there's a way to get it to spawn oceans or something)
Better Sorage vs Iron Backpacks
Artifacts
ArsMagica2
Gany's Nether

Overall what's remaining/issues:
0. Pack on the server side starts. 
1. Needs making a client and test connecting.
2. Reika stuff is commented out - on adding DragonAPI server crashes with marvelous error. Needs investigation/fixing/googling etc.
3. Check not done stuff above.

**Comment by the-vindex** [comment]
After testing point 2 I've determined that conflict is with Thaumic Infusion. I've commented it out and the rest of the mods has loaded ok.

In terms of reika mods, I'll add Rotary, CrC and Reactor Craft.
Now onward to ID conflicts - Chromatic conflicts with BoP in terms of biomes and with something else in enchantments. 

I don't have any of these changes pushed to PR yet.

**Comment by the-vindex** [comment]
Update:
- Rotary, CrC and Reactor Craft included in the pack
- ID conflicts solved
- Tropicraft was unpacked as thrid party
- Pinned AE2 to Rev2 with few other mods due to crash of Chromatic (we did the same in E18 in TPPI2)
- pack is starting on both server and client side, connects to server

On pending topics:

1. Needs making a client and test connecting. *[Done]*
2. Reika stuff is commented out - on adding DragonAPI server crashes with marvelous error. Needs investigation/fixing/googling etc.  *[Done]*
3. Check not done stuff in terms of mods.  *[Still not done, needs decisions]*
4. Check pull request. @Castone22 
5. Check dirty hack in Web.kt. @Baughn 
6. Check Minetweaker scripts, some seem to raise some errors as mods where removed.

@Castone22 Please deploy for user torture with usual caveats.

**Comment by Baughn** [comment]
The dirty hack is fine. I'm going to rewrite cursetool before E23, in part for better integration (it should be automatic, and faster), so whatever you do to it now doesn't matter.

**Comment by the-vindex** [comment]
I'm working on minetweaker scripts.

**Comment by Castone22** [comment]
+ Realistic Terraingen
+ Iron Backpacks (apparently better storage is crashy)
+ Ars Magica 2
+ Artifacts
- Gany's Nether
- Better Storage

**Comment by the-vindex** [comment]
Update
- RWG won't be added, RTG will be kept
- Iron Backpacks added
- AM2 added
- Artifacts - jar added, not included in the pack yet due to discussions
- Removed Flamingo

These were not in the pack, so not present:
Gany's Nether
Better Storage

**Comment by Castone22** [comment]
This work seems done.
